БЭМ разметка catalog.html и изменение названий БЭМ блоков в index.html
htmlacademy-adaptive/1518577-cat-energy-21 pull request #4
Opened 2020-12-11 16:31 UTC by TSergey123

в index.html изменил названия классов основных блоков header, main и footer тк вроде как лучше понял принцип БЭМ:)
Сделал разметку catalog.html
Вопрос: "У меня страница каталог - <html class="catalog" lang="en">
пере использовать блоки футера и хедера с основной страницы, если по итогу они буду называть page__footer и page__header?
 
Когда мы потом будем разбивать css на разные файлы, правильней же будет использовать один файл футера для всех страниц или для каждого футера каждой страницы будет отдельный файл?"
Спрашивал уже в вк, но думаю глядя на реквест вопрос станет понятней

2020-12-12 14:16 UTC, mikhin commented
@TSergey123, кстати, в этом задании должна быть размечена форма, а не каталог =)

2020-12-12 14:28 UTC, TSergey123 commented
> @TSergey123, кстати, в этом задании должна быть размечена форма, а не каталог =)

Дааа. Прости пожалуйста) я тоже заметил когда отправлял, но до понедельника вряд-ли до компа доберусь(

2020-12-12 14:31 UTC, mikhin requested changes

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +      <section class="goods">
Касается всех страниц

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +                <tr class="good-description__line">
`__row`

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +                  <td class="good-description__item">Масса</td>
Непонятно почему и определение и расшифровка называются безликим `item`

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +            <div class="good">
Непохоже по дизайну, что это тоже карточка товара, значит должен быть другой БЭМ-блок

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +              <span class="good__add">+</span>
По коду непонятно что это за элемент и для чего нужен

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +              <h2 class="additional-ingredient__title">Сахарозаменитель</h2>
Должен быть другой уровень заголовка)

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +              <table class="additional-ingredient__description">
Вот тут таблица кстати не вынесена в отдельный БЭМ-блок и вроде бы это норм

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +                <tr class="additional-ingredient__line">
`__row`

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +                  <td class="additional-ingredient__item">
Непонятно почему и определение и расшифровка называются безликим item

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +      <section class="adress">
`address`

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +              <button type="button" class="button">Заказать</button>
ТЗ намекает на другую чутка семантику https://up.htmlacademy.ru/adaptive/21/project/cat-energy#cat-energy-6-2

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +          <div class="footer-academy">
Непонятный нейминг

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +              <h3 class="footer-academy__title">html</h3>
Непонятно зачем разбито на два элемента и почему оба заголовки, такого не может быть)

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +            <ul class="footer-social__list">
Давай сделаем эти соцсети отдельным БЭМ-блоком)

2020-12-12 14:31 UTC, mikhin commented on source/catalog.html
> +        <div class="adress__image">
Кстати, может картинке дополнительный контейнер и не нужен

2020-12-14 10:16 UTC, TSergey123 commented on source/catalog.html
> +            <ul class="main-nav__list site-list">
изменил на user-nav

2020-12-14 10:18 UTC, TSergey123 commented on source/catalog.html
> +                <a
не должен быть ссылкой или ссылкой disabled? В любом случае, ссылку убрал, теперь это <li class="user-nav__item user-nav__item--active">Главная</li> или оставить только user-nav__item--active ?

2020-12-14 10:20 UTC, TSergey123 commented on source/catalog.html
> +                  >Главная</a
Честно говоря я не специально) Не знаю из-за чего так получается, но скобка переносится при сохранении

2020-12-14 10:21 UTC, TSergey123 commented on source/catalog.html
> +<html class="catalog" lang="ru">
Ну что-то вроде. Спасибо)

2020-12-14 10:22 UTC, TSergey123 commented on source/catalog.html
> +    <main class="catalog-main">
ну можно изменить на `catalog-main-block` но ты говорил, что слово блок использовать не совсем верно, так что даже не знаю на что заменить. На главной странице у тэга main стоит класс `page-main`

2020-12-14 10:23 UTC, TSergey123 commented on source/catalog.html
> +      <section class="goods">
`goods-block` - будет лучше?

2020-12-14 10:24 UTC, TSergey123 commented on source/catalog.html
> +              <div class="good__image">
`good__image-block` ?

2020-12-14 10:27 UTC, TSergey123 commented on source/catalog.html
> +              <h2 class="good__title">Cat Energy PRO 500 г</h2>
Заменил на `h3`

2020-12-14 10:34 UTC, TSergey123 commented on source/catalog.html
> +              <table class="good-description">
заменил на `good__description`

2020-12-14 10:35 UTC, TSergey123 commented on source/catalog.html
> +                <tr class="good-description__line">
Заменил на `good__description-row`

2020-12-14 10:35 UTC, TSergey123 commented on source/catalog.html
> +                  <td class="good-description__item">Масса</td>
Заменил на `good__description-definition` и `good__description-decryption`

2020-12-14 10:39 UTC, TSergey123 commented on source/catalog.html
> +            <div class="good">
Вот тоже долго сомневался, но долго посмотрев на макет, понял, что вроде как разметка одинаковая. Так что решил оставить так же. Сейчас заменю

2020-12-14 10:41 UTC, TSergey123 commented on source/catalog.html
> +            <div class="good">
заменил на `<li class="goods__list-item">
            <div class="good-show">`

2020-12-14 10:44 UTC, TSergey123 commented on source/catalog.html
> +              <span class="good__add">+</span>
ты про span + ? 
Я понимаю, что там по итогу будет плюс нарисован в css, но на момент разметки вроде неправильно оставлять элемент пустым.
Или речь про название? заменил на `good-show__plus`, так же, как он называется в макете

2020-12-14 10:46 UTC, TSergey123 commented on source/catalog.html
> +              <h2 class="additional-ingredient__title">Сахарозаменитель</h2>
Заменил на `h3`

2020-12-14 10:48 UTC, TSergey123 commented on source/catalog.html
> +              <table class="additional-ingredient__description">
Надо вынести или так и оставить? 
В разделе с товарами я тоже не выносил в отдельный блок

2020-12-14 10:49 UTC, TSergey123 commented on source/catalog.html
> +                <tr class="additional-ingredient__line">
- [ ]

2020-12-14 10:53 UTC, TSergey123 commented on source/catalog.html
> +      <section class="adress">
- [ ] `<a href="#" class="button-link">Заказать</a>`

2020-12-14 10:54 UTC, TSergey123 commented on source/catalog.html
> +              <button type="button" class="button">Заказать</button>
- [x] `<a href="#" class="button-link">Заказать</a>`

2020-12-14 10:57 UTC, TSergey123 commented on source/catalog.html
> +          <div class="footer-academy">
- [X] `<div class="site-author">`

2020-12-14 10:58 UTC, TSergey123 commented on source/catalog.html
> +              <h3 class="footer-academy__title">html</h3>
- [X]  `<h3 class="site-author__title">HTML<br>Academy</h3>`

2020-12-14 11:00 UTC, TSergey123 commented on source/catalog.html
> +            <ul class="footer-social__list">
ul сделать отдельным блоком?

2020-12-14 11:09 UTC, TSergey123 commented on source/catalog.html
> +        <div class="adress__image">
На прошлом интенсиве говорили, что картинка всегда должна находится внутри блока на случай если картинка не прогрузится. Так что пускай будет)

2020-12-14 13:08 UTC, TSergey123 commented on source/catalog.html
> +                  class="good__icon"
изменил на `<div class="good__image-block">
                <img
                  class="good__image"
                  src="https://place-hold.it/68x86"
                  alt="Банка корма Cat Energy"
                />`

2020-12-14 13:15 UTC, mikhin commented on source/catalog.html
> +                <a
Не, сейчас у тебя получилась сильно вариативная разметка, т.е. появление еще одного элемента (ссылки) внутри элемента списка зависит от активности элемента. Не очень удобно. Распространенный способ — делать на активном элементе вместо ссылки span.

2020-12-14 13:15 UTC, mikhin commented on source/catalog.html
> +            <ul class="main-nav__list site-list">
гораздо лучше, да

2020-12-14 13:16 UTC, mikhin commented on source/catalog.html
> +                  >Главная</a
Видимо надо настроить твой редактор, который форматирует текст при сохранении, чтобы именно это форматирование он не вносил) Если не получится, то ну и ладно)

2020-12-14 13:16 UTC, mikhin commented on source/catalog.html
> +    <main class="catalog-main">
А чем отличаются page-main и catalog-main с точки зрения раскладки страницы? За что они отвечают, какая у них функция? Можно ли сделать единый блок, который будет на всех страницах?

2020-12-14 13:17 UTC, mikhin commented on source/catalog.html
> +      <section class="goods">
`block` не надо использовать вообще никогда, т.к. смысла больше не становится, а надо чтобы было больше смысла. Например, `goods-list`

2020-12-14 13:18 UTC, mikhin commented on source/catalog.html
> +              <div class="good__image">
нет) Див — это абстрактная обертка по семантике. Почему-то вдруг она названа `image`. Чисто с точки зрения чтения кода становится непонятно, приходится открывать браузер и смотреть) Например можно назвать `__image-content`

2020-12-14 13:18 UTC, mikhin commented on source/catalog.html
> +                  class="good__icon"
Почти да =) про див написал выше)

2020-12-14 13:19 UTC, mikhin commented on source/catalog.html
> +              <h2 class="good__title">Cat Energy PRO 500 г</h2>
ага)

2020-12-14 13:19 UTC, mikhin commented on source/catalog.html
> +              <table class="good-description">
окей)

2020-12-14 13:20 UTC, mikhin commented on source/catalog.html
> +            <div class="good">
`good-show` не очень понятное имя, но ок, давай так оставим

2020-12-14 13:20 UTC, mikhin commented on source/catalog.html
> +              <span class="good__add">+</span>
> но на момент разметки вроде неправильно оставлять элемент пустым.

как раз правильно. Ты же просто размечаешь структуру страницы. Если какого-то элемента не должно быть в контенте и в структуре его не надо специально размечать, чтоб потом удалять)

2020-12-14 13:20 UTC, mikhin commented on source/catalog.html
> +              <h2 class="additional-ingredient__title">Сахарозаменитель</h2>
окей)

2020-12-14 13:21 UTC, mikhin commented on source/catalog.html
> +              <table class="additional-ingredient__description">
Выносил, у тебя был `good-description`. Тут можно оставить сейчас как есть)

2020-12-14 13:21 UTC, mikhin commented on source/catalog.html
> +              <button type="button" class="button">Заказать</button>
Ага, но имя стало странное — «кнопка-ссылка», но давай пока вот так оставим

2020-12-14 13:22 UTC, mikhin commented on source/catalog.html
> +          <div class="footer-academy">
ага, гораздо лучше, но можно написать `copyright`

2020-12-14 13:22 UTC, mikhin commented on source/catalog.html
> +              <h3 class="footer-academy__title">html</h3>
Лучше стало, да, но пока непонятно нужен ли br

2020-12-14 13:22 UTC, mikhin commented on source/catalog.html
> +            <ul class="footer-social__list">
Ага

2020-12-14 13:22 UTC, mikhin commented on source/catalog.html
> +        <div class="adress__image">
окей)

2020-12-14 13:23 UTC, mikhin commented on source/catalog.html
> +        <div class="adress__image">
но мотивация странная, я ее не понял

2020-12-14 13:24 UTC, TSergey123 commented on source/catalog.html
> +                <a
` <li class="user-nav__item">
                <span
                  class="user-nav__item-content user-nav__item-content--active"
                  >Главная</span
                >
              </li>`

2020-12-14 13:25 UTC, TSergey123 commented on source/catalog.html
> +    <main class="catalog-main">
Понял. Значит и там и там page-main

2020-12-14 13:26 UTC, TSergey123 commented on source/catalog.html
> +      <section class="goods">
goods-list идет двумя строками позже)

2020-12-14 13:27 UTC, TSergey123 commented on source/catalog.html
> +      <section class="goods">
поменяю на catalog-goods

2020-12-14 13:31 UTC, TSergey123 commented on source/catalog.html
> +      <section class="goods">
`<div class="good">` оставлю. Хотел поменять на good-card
но дальше будут такие название как `<tr class="good-card__description-row">` ну уже кажется будет слишком много букв)

2020-12-14 14:03 UTC, merged