БЭМ разметка страницы формы
htmlacademy-adaptive/1518577-cat-energy-21 pull request #5
Opened 2020-12-15 12:40 UTC by TSergey123

не уверен только в наименовании блоков внутри формы
` <div class="cat-info">` `<div class="chosen-program">` и тд. Не уверен что они должны быть бэм блоками если поля внутри привязаны к форме, а не к блоку. Или надо поля назвать с привязкой к блоку... Вообщем не уверен, но где-то тут я точно ошибся)

2020-12-15 15:41 UTC, mikhin requested changes

2020-12-15 15:41 UTC, mikhin commented on source/form.html
> +          <div class="cat-info">
Напишу об этом здесь, это касается и других элементов формы: сейчас вот таким классом мы жестко прибиваем в нейминге функционал формы к предполагаемому контенту. Т.е. мы видим в дизайне, что это форма про кота и корм и сразу такие «ага, это форма про кота и корм». Надо помыслить шире и на будущее, подумать как проект может развиваться. Например, завтра дизайнер принесет такую же форму, но уже про собаку, или про какое-нибудь мероприятие для хозяек слонов. И тогда все наши БЭМ-блоки и весь наш нейминг сразу не подойдет. Потому что не может композиция формы включать в себя БЭМ-блок с именем `cat-info` и быть про собак или слонов. И надо будет копировать все БЭМ-блоки еще раз отдельно или переименовывать эти, придумывая более универсальные имена. Поэтому правильно в данном случае будет поступить так: в именовании и проектировании формы и её элементов абстрагироваться от бизнес-терминов и спроектировать и проименовать в рамках терминологии нашей с тобой профессиональной предметной области — «разработка интерфейсов». Например, это группа полей тогда будет не `cat-info`, а `field-group`. Т.е. как бы разложить интерфейс на стандартные какие-то типовые элементы, как болванки на заводе, и превратить их в БЭМ-блоки. И тогда можно будет брать любой контент и собирать интерфейс для него из готовых заранее БЭМ-блоков.

2020-12-15 15:41 UTC, mikhin commented on source/form.html
> +              class="form-fill__label form-fill__label--cat-name"
Кажется, что БЭМ-модификаторы здесь не нужны вовсе нигде.

2020-12-15 15:41 UTC, mikhin commented on source/form.html
> +              for="name"
Т.к. у нас кастомный дизайн контролов формы (радио-кнопок и чек-боксов) и реализовывать мы будем через очень определенным способом в CSS, то лучше заранее сгруппировать эти сущности в один БЭМ-блок.

2020-12-15 15:41 UTC, mikhin commented on source/form.html
> +              for="slimm"
Опечатка

2020-12-15 15:41 UTC, mikhin commented on source/form.html
> +            <input
Непонятно почему ранее сначала шел лейбл, а потом инпут, а тут наоборот.

2020-12-15 15:41 UTC, mikhin commented on source/form.html
> +              cols="1"
Эти атрибуты касаются размеров формы. Давай их отсюда уберем и потом сделаем размеры через CSS.

2020-12-15 15:41 UTC, mikhin commented on source/form.html
> +            <button type="button" class="button">Отправить заявку</button>
Здесь как раз нужен type=submit =)

2020-12-15 15:41 UTC, mikhin commented on source/form.html
> +            <div class="footer__image-content">
Чисто по неймингу и по коду непонятно что значит «картинка в футере». Что за картинка?) И еще кажется, что это такой же логотип по дизайну, как в шапке. Поэтому это намек на повторное использование в обоих местах одного и того же БЭМ-блока)

2020-12-15 16:00 UTC, TSergey123 commented on source/form.html
> +        <a href="#" class="page-header_logo-energy">
id))
Поправил. Плюс у картинок изменил названия на `page-header__logo-energy` было просто `logo-energy`

2020-12-15 16:08 UTC, TSergey123 commented on source/form.html
> +          <div class="cat-info">
ого. Окей. переделал на field-group

2020-12-15 16:09 UTC, TSergey123 commented on source/form.html
> +              class="form-fill__label form-fill__label--cat-name"
Согласен. Но я пытался))

2020-12-15 16:14 UTC, TSergey123 commented on source/form.html
> +              for="name"
Не очень понял. Я подписал все чек боксы и радио баттоны `class="standart-form__checkbox standart-form__checkbox-sugar"`

2020-12-15 16:15 UTC, TSergey123 commented on source/form.html
> +            <input
Ну в макете так. Или правильнее потом будет поменять местами через ордер?

2020-12-15 16:16 UTC, TSergey123 commented on source/form.html
> +              cols="1"
Понял. Думал они обязательные для textarea

2020-12-15 16:24 UTC, TSergey123 commented on source/form.html
> +            <div class="footer__image-content">
убрал блок image-content, оставил добавил ссылку        `<a href="#" class="primary-logo-link">` и у логотипа поменял класс на ```
<img
            src="https://place-hold.it/101x18"
            width="101"
            height="18"
            alt="Заголовок сайта Cat Energy"
            class="primary-logo-link__logotype"
        />
```

так получается два одинаковых блока в шапке и в футере

2020-12-16 13:06 UTC, mikhin commented on source/form.html
> +            <input
Возможно да, лучше сейчас сделать исходный код однообразным

2020-12-16 13:07 UTC, mikhin commented on source/form.html
> +              for="name"
Нужно сделать кастомные контролы отдельными БЭМ-блоками

2020-12-16 19:01 UTC, mikhin approved these changes
Эти моменты лучше бы поправить в следующей домашке)

2020-12-16 19:01 UTC, mikhin commented on source/form.html
> +              <a href="#" class="primary-logo-link">
Тоже самое — по коду неясно для чего нужен БЭМ-блок

2020-12-16 19:01 UTC, merged