Пробная попытка стилизовать первую страницу
htmlacademy-adaptive/1518577-cat-energy-21 pull request #6
Opened 2020-12-17 17:09 UTC by TSergey123

Просто хочу понять, правильно ли я понял основной подход.
А еще я походу неправильно разметил шапку в index.html

2020-12-21 20:27 UTC, mikhin requested changes

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/social-list.less
> +  padding: 1em;
Лучше указать в пикселях

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/social-list.less
> +  padding: 1em;
Касается всех файлов)

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/user-nav.less
> +  font-family: "Oswald", "Arial", sans-serif;
Лучше указать на селекторе блока)

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/user-nav.less
> +  width: 100%;
Это пока не нужно, и непонятно зачем)

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/social-list.less
> +  justify-content: space-around;
Лучше не полагаться на это, а самому задавать нужные отступы в таких случаях)

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/programs.less
> +  outline: 1px solid @basic-black;
Давай отовсюду уберем и бахнем временно где-нибудь в одном месте вот так:
```
* {
outline: 1px solid @basic-black;
}
```
и еще будем комментить (отключать) это перед пушем, при завершении задания, чтобы проверять было удобнее)

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/program-card.less
> +  font-family: "Oswald", "Arial", sans-serif;
Вроде уже на блоке висит, значит тут не нужно)

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/program-card.less
> +  font-weight: 400;
Кажется это избыточно

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/page-body.less
> +// page-body
Такие комменты нужно убрать, т.к. они не несут пользы)

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/header-info.less
> +  top: -110px;
Позиционирование выглядит очень подозрительно, да и сейчас не нужно по заданию. Давай уберем пока его?

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/header-info.less
> +  font-size: 14px;
В 99% случаев font-size и line-height должны указываться в паре)

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/header-info.less
> +  opacity: 0.1;
По коду непонятно зачем это нужно)

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/button.less
> +.button__link {
Очень странное имя класса, по коду непонятно зачем нужен такой БЭМ-элемент

2020-12-21 20:27 UTC, mikhin commented on source/less/blocks/about-card.less
> +.about-card__image-content {
Правильное имя класса! 👍

2020-12-21 20:27 UTC, mikhin commented on source/index.html
> +                  <img src="img/icon_vkontakte.png" alt="ссылка на вконтакте">
`Ссылка на «Вконтакте»`

2020-12-21 20:27 UTC, mikhin commented on source/index.html
> +                ><img src="img/icon_instagram.svg" alt="ссылка на инстаграм"></a>
`Ссылка на Инстаграм`

2020-12-21 20:27 UTC, mikhin commented on source/index.html
> +                ><img src="img/icon_facebook.svg" alt="Ссылка на фейсбук"></a>
`Фейсбук`

2020-12-21 20:27 UTC, mikhin commented on source/index.html
> +              alt="Заголовок Cat Energy"
Непонятно что значит `Заголовок`

2020-12-21 20:27 UTC, mikhin commented on source/index.html
> +            <div class="address-description__info">
Обертки не нужны в обоих случаях

2020-12-21 20:27 UTC, mikhin commented on source/index.html
> +              затраты на питание: 15 000 руб.
С большой буквы

2020-12-21 20:27 UTC, mikhin commented on source/index.html
>                    <img
Давай сделаем это псевдоэлементами потом, а сейчас пока уберем из разметки)

2020-12-21 20:27 UTC, mikhin commented on source/index.html
>                    <img
Касается всех декоративных (интерфейсных) изображений в проекте)

2020-12-21 20:27 UTC, mikhin commented on source/index.html
> +          <div class="header-info__button button">
Не должны хотеть на `div` вешать класс `button`.

2020-12-21 20:27 UTC, mikhin commented on source/index.html
> +            <a class="header-info__choose button__link" href="#"
`button__link` по коду непонятно как такое может быть, что внутри кнопки лежит ссылка)

2020-12-22 10:34 UTC, TSergey123 commented on source/less/blocks/social-list.less
> +  justify-content: space-around;
Я оставлю так до момента выравнивания пиксель в пиксель.

2020-12-22 10:43 UTC, TSergey123 commented on source/less/blocks/program-card.less
> +  font-weight: 400;
font-weight: 400?

Вообще хотел спросить, 
У нас два шрифта, OswaldRegular и OswaldMedium
Как узнать какой у них font-weight?

2020-12-22 10:44 UTC, TSergey123 commented on source/less/blocks/page-body.less
> +// page-body
"каждому БЭМ-блоку должен соответствовать отдельный препроцессорный файл;"
Но оставлять файлы пустыми нельзя, а написать в них пока что нечего.
Лучше вообще их удалить или оставить как по заданию?

2020-12-22 11:00 UTC, TSergey123 commented on source/less/blocks/header-info.less
> +  opacity: 0.1;
В макете используется цвет @opacity-green: rgba(104, 183, 56, 0.85);
Но я же не могу просто задать этот цвет, не дав опасити самой картинке. Как раз тоже хотел спросить как правильно тут поступить

2020-12-22 11:15 UTC, TSergey123 commented on source/less/blocks/button.less
> +.button__link {
button__content?

2020-12-22 11:16 UTC, TSergey123 commented on source/less/blocks/button.less
> +.button__link {
button__item?

2020-12-22 11:17 UTC, TSergey123 commented on source/less/blocks/about-card.less
> +.about-card__image-content {
ахахаха))) так удивляет, что я что-то сделал правильно, что выносишь в отдельный комментарий))

2020-12-22 13:45 UTC, TSergey123 commented on source/index.html
>                    <img
Все икноки будут добавляться через ::after/before?

2020-12-22 13:46 UTC, TSergey123 commented on source/index.html
>                    <img
надо убрать img или div?

2020-12-22 13:58 UTC, mikhin commented on source/less/blocks/social-list.less
> +  justify-content: space-around;
окей)

2020-12-22 13:58 UTC, mikhin commented on source/less/blocks/program-card.less
> +  font-weight: 400;
обычно regular это 400, а medium это 500

2020-12-22 13:59 UTC, mikhin commented on source/less/blocks/page-body.less
> +// page-body
Если в них нечего писать, то их нужно удалить)

> каждому БЭМ-блоку должен соответствовать отдельный препроцессорный файл

имеется ввиду, что если уж селекторы и стили есть, то они должны быть разделены по разным бэм-блокам по файлам)

2020-12-22 14:00 UTC, mikhin commented on source/less/blocks/header-info.less
> +  opacity: 0.1;
не очень понял вопрос

2020-12-22 14:01 UTC, mikhin commented on source/less/blocks/button.less
> +.button__link {
не, тут странное имя класса намекает на странную структуру в HTML, я где-то тут в ПР писал об этом коммент: не может быть такой структуры, что по неймингу в кнопке лежит ссылка) это типа как в картинке лежит таблица или в шапке сайта лежит подвал, т.е. противоречие) надо переработать структуру HTML этого БЭМ-блока, чтоб он был ясный и понятный, а уже отсюда и правильный нейминг придет сам)

2020-12-22 14:02 UTC, mikhin commented on source/less/blocks/about-card.less
> +.about-card__image-content {
Не, ну тут суть в том, что нет задачи только писать правки. Тут есть задача просто общаться про код, отмечая разные моменты: и достойные и те, что могли бы быть лучше)

2020-12-22 14:03 UTC, mikhin commented on source/index.html
>                    <img
> Все икноки будут добавляться через ::after/before?

Да, нужно привыкнуть к мысли, что HTML не должен знать про декор интерфейса ничего вообще никогда) потому что HTML это про документ, его структуру и контент)

2020-12-22 14:03 UTC, mikhin commented on source/less/blocks/button.less
> +.button__link {
https://github.com/htmlacademy-adaptive/1518577-cat-energy-21/pull/6#discussion_r546914227

2020-12-22 20:26 UTC, mikhin commented
<img width="167" alt="Снимок экрана 2020-12-22 в 23 25 33" src="https://user-images.githubusercontent.com/38258318/102930250-21adc780-44ad-11eb-8790-112c3da31727.png">
<img width="208" alt="Снимок экрана 2020-12-22 в 23 25 49" src="https://user-images.githubusercontent.com/38258318/102930253-22def480-44ad-11eb-823a-ebe077de475e.png">

Одно из повторяющихся изображений нужно удалить

2020-12-22 20:27 UTC, mikhin commented
<img width="174" alt="Снимок экрана 2020-12-22 в 23 26 10" src="https://user-images.githubusercontent.com/38258318/102930278-2ecab680-44ad-11eb-989c-ff96a03518cb.png">

Эта картинка, кажется, экспортирована неверно)

2020-12-22 20:28 UTC, mikhin commented
<img width="1279" alt="Снимок экрана 2020-12-22 в 23 28 22" src="https://user-images.githubusercontent.com/38258318/102930400-676a9000-44ad-11eb-8f0c-ef87cf624fc1.png">

В консоли есть ошибки, которые нужно устранить

2020-12-22 20:31 UTC, mikhin approved these changes

2020-12-22 20:31 UTC, mikhin commented on package.json
> +    "eslint-config-prettier": "^7.1.0",
Давай пока в рамках курса не будем добавлять никаких библиотек самостоятельно, чтобы не сломать сборку, которую настроила Академия)

2020-12-22 20:31 UTC, mikhin commented on source/less/blocks/address.less
> +  margin-top: 10px;
Сейчас это можно оставить, но на будущее — на селекторах самих БЭМ-блоков не должны висеть CSS-правила «внешней геометрии» (position: absolute, margin, vertical-align, flex-shrink, и т.д.), потому что это означает что блок «знает» и зависит от каких-то CSS-правил своего родителя и это значит что он не независим, а такого мы не должны хотеть. Мы должны хотеть проектировать абсолютно независимые блоки по методологии БЭМ)

2020-12-22 20:32 UTC, mikhin commented
ПР принимаю, но эти правки надо поправить в следующем ПР)

2020-12-22 20:32 UTC, merged