module3-task2 Первая попытка
htmlacademy-adaptive/1518577-cat-energy-21 pull request #7
Opened 2020-12-24 16:13 UTC by TSergey123

Не смог понять из-за чего ошибки в консоли. Вроде все правильно указал. а ошибки с подключением стилей остались

2020-12-25 07:10 UTC, mikhin requested changes

2020-12-25 07:10 UTC, mikhin commented on source/form.html
> +        <section class="program-choose">
Как-то маловато контента внутри для `section`

2020-12-25 07:10 UTC, mikhin commented on source/form.html
> +                <input class="standart-form__radio" type="radio" id="slim" name="standart-form__radio" />
В атрибуте name должно храниться знание о конкретных данных, а не об интерфейсе, потому что это знание будет отправлено на бэкенд)

2020-12-25 07:10 UTC, mikhin commented on source/form.html
> +            <div class="left-comment field-list">
Непонятно что значит `left-comment`

2020-12-25 07:10 UTC, mikhin commented on source/form.html
> +              <h2 class="checkbox-list__title field-list__title">Дополнительно</h2>
Непонятно зачем сразу два БЭМ-элемента

2020-12-25 07:10 UTC, mikhin commented on source/form.html
> +            <ul class="checkbox-list field-list standart-form__checkbox-list">
Два БЭМ-блока + БЭМ-элемент — итого три сущности. Кажется это многовато)

2020-12-25 07:10 UTC, mikhin commented on source/less/blocks/address.less
> +.address--colorized {
Давай сделаем этот стиль по умолчанию, без модификатора

2020-12-25 07:10 UTC, mikhin commented on source/less/blocks/field-list.less
> +  height: 46px;
Зачем тут высота?

2020-12-25 07:10 UTC, mikhin commented on source/less/blocks/field-textarea.less
> +.field-textarea::placeholder {
Давай убирать всегда псевдоклассы и псевдоселекторы за амперсанд)

2020-12-25 07:10 UTC, mikhin commented on source/less/blocks/raduibutton-list.less
> +  line-height: 18px;
Непонятно почему тут line-height нужен без font-size

2020-12-25 07:10 UTC, mikhin commented on source/less/blocks/standart-form.less
> +.standart-form__required {
`__required-mark`

2020-12-25 07:11 UTC, mikhin commented
<img width="268" alt="Снимок экрана 2020-12-25 в 10 10 10" src="https://user-images.githubusercontent.com/38258318/103124649-7ada4e80-4699-11eb-9f3e-66bf0b901898.png">

А точно все фоновые изображение и цвета стилизованы как написано в задании?

2020-12-25 07:11 UTC, mikhin commented
Ошибки в консоли нужно устранить)

<img width="1280" alt="Снимок экрана 2020-12-25 в 10 10 04" src="https://user-images.githubusercontent.com/38258318/103124689-95142c80-4699-11eb-9a37-34d29e490765.png">

2020-12-25 11:25 UTC, TSergey123 commented on source/form.html
> +        <section class="program-choose">
article лучше? или просто див пойдет?

2020-12-25 11:42 UTC, TSergey123 commented on source/less/blocks/address.less
> +.address--colorized {
Ну вот тут не знаю. на одной странице он закрашен, на других нет. Модификаторы же и существуют, что бы как раз акцентировать внимание на цветах, размерах и тд.

2020-12-25 11:43 UTC, TSergey123 commented on source/less/blocks/field-list.less
> +  height: 46px;
Ой. Я игрался с размерами, что бы разобраться как делать отступы и забыл удалить

2020-12-29 11:45 UTC, merged

2020-12-29 11:46 UTC, mikhin commented on source/form.html
> +          <h3 class="program-choose__text">Заполните анкету, и мы подберем программу питания для вашего кота</h3>
Непонятно по коду почему заголовок называется text в классе, плюс кажется по семантике он тут не нужен

2020-12-29 11:46 UTC, mikhin commented on source/form.html
> +          <div class="comment-section field-list">
По коду непонятно зачем тут два БЭМ-блока одновременно

2020-12-29 11:46 UTC, mikhin commented on source/form.html
> +            <div class="container">
Внутри UL не могут лежать никакие элементы кроме LI

2020-12-29 11:46 UTC, mikhin commented on source/less/blocks/field-list.less
> +  text-transform: none;
Это ведь значение по умолчанию, зачем оно тут?

2020-12-29 11:46 UTC, mikhin commented on source/less/blocks/page-body.less
> +  overflow-x: hidden;
Непонятно зачем это нужно.

2020-12-29 13:21 UTC, TSergey123 commented on source/form.html
> +          <div class="comment-section field-list">
как-то странно. 
я делал так, но даже не коммитил в таком состоянии
отправлял я такой вариант
` <div class="field-list__head">
                <h2 class="field-list__title">Комментарий</h2>
              </div>
              <textarea class="field-textarea" placeholder="Расскажите обо всех повадках кота" name="textarea-comment" id="textarea-comment"></textarea>
            </div>`

2020-12-29 13:29 UTC, TSergey123 commented on source/less/blocks/field-list.less
> +  text-transform: none;
Я применил uppercase к блоку field-list. мне либо надо применить uppercase к 5 модификаторам либо один раз ко всему блоку и для одного нужного модификатора сделать none. Решил так будет правильнее не перегружать код

2020-12-29 13:31 UTC, TSergey123 commented on source/less/blocks/page-body.less
> +  overflow-x: hidden;
думал так получится избавиться от скролла из-за картинок. Но не получилось(

2020-12-29 13:33 UTC, mikhin commented on source/less/blocks/page-body.less
> +  overflow-x: hidden;
мы не должны хотеть так думать и делать, потому что это не решение проблемы, а её сокрытие) т.е. надо решать проблему с картинками, а не отрубать скрол) на скрол в рамках этого задания можно было забить, потому что тут нет еще пока близкого к пиксель-перфекту)

2020-12-29 13:33 UTC, mikhin commented on source/less/blocks/field-list.less
> +  text-transform: none;
окей)